name: FLTK Janet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: rwtolbert/fltk-janet
          path: fltk-janet
      - uses: actions/checkout@v4
        with:
          repository: janet-lang/janet
          path: janet
      - uses: actions/checkout@v4
        with: 
          repository: janet-lang/spork
          path: spork
      - name: Build janet
        run: cd janet && PREFIX=../local make install && ../local/bin/janet -v
      - name: Build spork
        run: cd spork && ../local/bin/janet --install .
      - name: Build fltk-janet
        run: ls $HOME && echo "../local/bin" >> $GITHUB_PATH && cd fltk-janet && ../local/lib/janet/bin/janet-pm build
